In [4]:
import numpy as np
import pandas as pd

# =========================================================
# GEOMETRY DESCRIPTOR EXTRACTION PROGRAM
# =========================================================
#
# Extracts:
#
# 1. M-M Distance
# 2. Shortest Intramolecular M-N Distance
# 3. Monomer Centroid Slippage
#
# Slippage =
# perpendicular displacement between monomer centroids
# relative to M-M interaction axis
#
# Monomers assigned geometrically
# using nearest-metal criterion
#
# Heavy atoms only used for centroids
#
# =========================================================

# ---------------------------------------------------------
# INPUT FILE
# ---------------------------------------------------------

coord_file = "All_Cu_Coordinates.txt"

# ---------------------------------------------------------
# READ FILE
# ---------------------------------------------------------

with open(coord_file, "r") as f:
    lines = f.readlines()

# ---------------------------------------------------------
# STORE COMPLEXES
# ---------------------------------------------------------

complexes = {}
current_complex = None

for line in lines:

    stripped = line.strip()

    # Detect complex header
    if stripped.startswith("Complex"):

        current_complex = stripped.split(":")[1].strip()
        complexes[current_complex] = []

    # Skip separators and blank lines
    elif stripped.startswith("=") or stripped == "":
        continue

    else:

        parts = stripped.split()

        if len(parts) == 4:

            atom = parts[0]

            x = float(parts[1])
            y = float(parts[2])
            z = float(parts[3])

            coord = np.array([x, y, z])

            complexes[current_complex].append(
                (atom, coord)
            )

# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------

def distance(a, b):

    return np.linalg.norm(a - b)

# ---------------------------------------------------------
# RESULTS
# ---------------------------------------------------------

results = []

# ---------------------------------------------------------
# PROCESS EACH COMPLEX
# ---------------------------------------------------------

for complex_name, atoms in complexes.items():

    # -----------------------------------------------------
    # IDENTIFY METALS
    # -----------------------------------------------------

    metal_atoms = []

    for atom, coord in atoms:

        if atom in ["Cu", "Ag", "Au"]:

            metal_atoms.append((atom, coord))

    # Must contain exactly two metals
    if len(metal_atoms) != 2:

        print(f"Skipping {complex_name} : metal issue")
        continue

    metal_symbol = metal_atoms[0][0]

    M1 = metal_atoms[0][1]
    M2 = metal_atoms[1][1]

    # -----------------------------------------------------
    # M-M DISTANCE
    # -----------------------------------------------------

    MM_distance = distance(M1, M2)

    # -----------------------------------------------------
    # GEOMETRIC MONOMER ASSIGNMENT
    # -----------------------------------------------------

    monomer1 = []
    monomer2 = []

    for atom, coord in atoms:

        d1 = distance(coord, M1)
        d2 = distance(coord, M2)

        if d1 <= d2:

            monomer1.append((atom, coord))

        else:

            monomer2.append((atom, coord))

    # -----------------------------------------------------
    # SHORTEST INTRAMOLECULAR M-N
    # -----------------------------------------------------

    N1_distances = []
    N2_distances = []

    for atom, coord in monomer1:

        if atom == "N":

            N1_distances.append(
                distance(M1, coord)
            )

    for atom, coord in monomer2:

        if atom == "N":

            N2_distances.append(
                distance(M2, coord)
            )

    # Skip problematic systems
    if len(N1_distances) == 0 or len(N2_distances) == 0:

        print(f"Skipping {complex_name} : N assignment issue")
        continue

    shortest_M1_N = min(N1_distances)
    shortest_M2_N = min(N2_distances)

    shortest_MN = (
        shortest_M1_N + shortest_M2_N
    ) / 2

    # -----------------------------------------------------
    # HEAVY-ATOM CENTROIDS
    # -----------------------------------------------------

    heavy_atoms_1 = []
    heavy_atoms_2 = []

    for atom, coord in monomer1:

        if atom != "H":

            heavy_atoms_1.append(coord)

    for atom, coord in monomer2:

        if atom != "H":

            heavy_atoms_2.append(coord)

    centroid1 = np.mean(
        heavy_atoms_1,
        axis=0
    )

    centroid2 = np.mean(
        heavy_atoms_2,
        axis=0
    )

    # -----------------------------------------------------
    # MONOMER SLIPPAGE
    # -----------------------------------------------------

    # M-M interaction axis

    MM_axis = M2 - M1

    MM_unit = (
        MM_axis / np.linalg.norm(MM_axis)
    )

    # Centroid displacement

    centroid_vector = (
        centroid2 - centroid1
    )

    # Projection along M-M axis

    projection_length = np.dot(
        centroid_vector,
        MM_unit
    )

    projection_vector = (
        projection_length * MM_unit
    )

    # Perpendicular component

    perpendicular_vector = (
        centroid_vector - projection_vector
    )

    slippage = np.linalg.norm(
        perpendicular_vector
    )

    # -----------------------------------------------------
    # STORE RESULTS
    # -----------------------------------------------------

    results.append({

        "Complex": complex_name,

        "Metal": metal_symbol,

        "M_M_Distance": round(
            MM_distance, 4
        ),

        "Shortest_M_N": round(
            shortest_MN, 4
        ),

        "Monomer_Slippage": round(
            slippage, 4
        )

    })

# ---------------------------------------------------------
# CREATE DATAFRAME
# ---------------------------------------------------------

df = pd.DataFrame(results)

# ---------------------------------------------------------
# DISPLAY SETTINGS
# ---------------------------------------------------------

pd.set_option(
    'display.max_rows',
    None
)

pd.set_option(
    'display.max_columns',
    None
)

# ---------------------------------------------------------
# DISPLAY RESULTS
# ---------------------------------------------------------

print(df)

# ---------------------------------------------------------
# OPTIONAL SAVE
# ---------------------------------------------------------

df.to_csv(
     "Geometry_Descriptors.csv",
     index=False
)

    Complex Metal  M_M_Distance  Shortest_M_N  Monomer_Slippage
0      Ag_1    Ag        3.0375        2.0693            1.0665
1      Ag_2    Ag        3.0125        2.0885            2.1310
2      Ag_3    Ag        3.0250        2.0650            4.0887
3      Ag_4    Ag        3.0125        2.0594            2.1595
4      Ag_5    Ag        3.0375        2.0685            2.1696
5      Ag_6    Ag        3.0375        2.0690            2.1351
6      Ag_7    Ag        3.0250        2.0795            1.0745
7      Ag_8    Ag        3.0125        2.0866            1.0339
8      Ag_9    Ag        2.9875        2.1056            2.1098
9     Ag_10    Ag        3.0000        2.0829            4.0853
10    Ag_11    Ag        3.0000        2.0768            2.1386
11    Ag_12    Ag        3.0125        2.0834            2.1466
12    Ag_13    Ag        3.0250        2.0833            2.1115
13    Ag_14    Ag        3.0125        2.0945            1.0405
14    Ag_15    Ag        3.0000        2.1108            0.9937
15    Ag_16    Ag        2.9750        2.1298            2.0848
16    Ag_17    Ag        2.9875        2.1089            4.0842
17    Ag_18    Ag        2.9875        2.1007            2.1129
18    Ag_19    Ag        3.0000        2.1051            2.1193
19    Ag_20    Ag        3.0125        2.1037            2.0833
20    Ag_21    Ag        3.0000        2.1163            0.9988
21    Ag_22    Ag        3.0750        2.0834            0.0399
22    Ag_23    Ag        3.0625        2.1087            1.1056
23    Ag_24    Ag        3.0500        2.0827            3.1939
24    Ag_25    Ag        3.0500        2.0822            1.1307
25    Ag_26    Ag        3.0750        2.0787            1.1302
26    Ag_27    Ag        3.0750        2.0769            1.1017
27    Ag_28    Ag        3.0625        2.0874            0.0506
28    Ag_29    Ag        2.9250        2.1300            3.3204
29    Ag_30    Ag        2.9250        2.1296            3.9221
30    Ag_31    Ag        2.9250        2.1334            5.4048
31    Ag_32    Ag        2.9250        2.1343            3.9460
32    Ag_33    Ag        2.9375        2.1287            3.9665
33    Ag_34    Ag        2.9250        2.1253            3.9470
34    Ag_35    Ag        2.9250        2.1294            3.3258
35    Ag_36    Ag        2.9625        2.1348            2.5009
36    Ag_37    Ag        2.9625        2.1366            3.1273
37    Ag_38    Ag        2.9750        2.1379            4.6779
38    Ag_39    Ag        2.9625        2.1408            3.1469
39    Ag_40    Ag        2.9625        2.1303            3.1616
40    Ag_41    Ag        2.9625        2.1264            3.1439
41    Ag_42    Ag        2.9625        2.1318            2.5038
42    Au_43    Au        3.1750        1.9632            1.0064
43    Au_44    Au        3.1500        1.9859            2.0558
44    Au_45    Au        3.1750        1.9547            3.9795
45    Au_46    Au        3.1750        1.9492            2.0770
46    Au_47    Au        3.1750        1.9712            2.0980
47    Au_48    Au        3.1750        1.9772            2.0684
48    Au_49    Au        3.1625        1.9839            1.0211
49    Au_50    Au        3.1500        1.9785            0.9723
50    Au_51    Au        3.1250        2.0021            2.0338
51    Au_52    Au        3.1500        1.9703            3.9737
52    Au_53    Au        3.1625        1.9642            2.0539
53    Au_54    Au        3.1500        1.9856            2.0750
54    Au_55    Au        3.1500        1.9911            2.0445
55    Au_56    Au        3.1375        1.9987            0.9870
56    Au_57    Au        3.1250        2.0036            0.9330
57    Au_58    Au        3.0875        2.0290            2.0114
58    Au_59    Au        3.1125        1.9956            3.9721
59    Au_60    Au        3.1250        1.9883            2.0287
60    Au_61    Au        3.1250        2.0093            2.0498
61    Au_62    Au        3.1250        2.0140            2.0189
62    Au_63    Au        3.1125        2.0233            0.9480
63    Au_64    Au        3.1625        2.0025            0.0288
64    Au_65    Au        3.1500        2.0224            1.0745
65    Au_66    Au        3.1625        1.9967            3.1318
66    Au_67    Au        3.1500        1.9925            1.0954
67    Au_68    Au        3.1625        2.0069            1.1096
68    Au_69    Au        3.1750        2.0102            1.0834
69    Au_70    Au        3.1625        2.0177            0.0430
70    Au_71    Au        3.0625        2.0455            3.2356
71    Au_72    Au        3.0750        2.0484            3.8367
72    Au_73    Au        3.0625        2.0443            5.3023
73    Au_74    Au        3.0750        2.0418            3.8484
74    Au_75    Au        3.0625        2.0452            3.8782
75    Au_76    Au        3.0625        2.0459            3.8619
76    Au_77    Au        3.0625        2.0471            3.2424
77    Au_78    Au        3.0625        2.0471            3.2424
78    Au_79    Au        3.0750        2.0762            3.0816
79    Au_80    Au        3.0750        2.0750            4.6192
80    Au_81    Au        3.0750        2.0746            3.0960
81    Au_82    Au        3.0625        2.0724            3.1185
82    Au_83    Au        3.0750        2.0711            3.1025
83    Au_84    Au        3.1250        2.0741            3.0936
84     Cu_1    Cu        2.6625        1.8068            1.0304
85     Cu_2    Cu        2.6375        1.8241            2.0924
86     Cu_3    Cu        2.6500        1.7995            3.8067
87     Cu_4    Cu        2.6500        1.7949            3.3631
88     Cu_5    Cu        2.7250        1.7922            2.2019
89     Cu_6    Cu        2.7000        1.8435            1.0250
90     Cu_7    Cu        2.7000        1.8609            2.1403
91     Cu_8    Cu        2.7125        1.8358            4.0787
92     Cu_9    Cu        2.7000        1.8304            3.5863
93    Cu_10    Cu        2.7000        1.8221            2.1492
94    Cu_11    Cu        2.7000        1.8536            0.9665
95    Cu_12    Cu        2.6875        1.8719            2.1252
96    Cu_13    Cu        2.7000        1.8470            4.0903
97    Cu_14    Cu        2.6875        1.8414            3.5932
98    Cu_15    Cu        2.7000        1.8310            2.1322
99    Cu_16    Cu        2.6875        1.8690            0.9184
100   Cu_17    Cu        2.6750        1.8883            2.1086
101   Cu_18    Cu        2.6875        1.8627            4.1050
102   Cu_19    Cu        2.6625        1.8568            3.5979
103   Cu_20    Cu        2.6875        1.8462            2.1150
104   Cu_21    Cu        2.7000        1.8601            0.0122
105   Cu_22    Cu        2.7000        1.8748            1.1170
106   Cu_23    Cu        2.7125        1.8546            3.1733
107   Cu_24    Cu        2.6875        1.8502            2.6412
108   Cu_25    Cu        2.6500        1.8412            1.1754
109   Cu_26    Cu        2.7375        1.8856            3.2098
110   Cu_27    Cu        2.7375        1.8871            3.8205
111   Cu_28    Cu        2.7250        1.8836            3.7512
112   Cu_29    Cu        2.7000        1.8809            4.9148
113   Cu_30    Cu        2.7500        1.8857            3.8480
114   Cu_31    Cu        2.7625        1.8877            3.8069
115   Cu_32    Cu        2.7750        1.8885            3.9177
116   Cu_33    Cu        2.7125        1.9167            3.1609
117   Cu_34    Cu        2.7125        1.9183            3.7756
118   Cu_35    Cu        2.7125        1.9160            5.2439
119   Cu_36    Cu        2.7000        1.9145            4.8464
120   Cu_37    Cu        2.7125        1.9161            3.8165
121   Cu_38    Cu        2.7250        1.9172            3.7822
122   Cu_39    Cu        2.7250        1.9155            3.7978
123   Cu_40    Cu        2.6875        1.9257            3.1352
124   Cu_41    Cu        2.6875        1.9274            3.7479
125   Cu_42    Cu        2.7250        1.9304            5.2477
126   Cu_43    Cu        2.6875        1.9241            4.8098
127   Cu_44    Cu        2.6875        1.9248            3.7895
128   Cu_45    Cu        2.7000        1.9255            3.7576
129   Cu_46    Cu        2.7000        1.9234            3.7797
130   Cu_47    Cu        2.6625        1.9390            3.0904
131   Cu_48    Cu        2.6625        1.9409            3.6937
132   Cu_49    Cu        2.6625        1.9397            5.1477
133   Cu_50    Cu        2.6625        1.9386            4.7453
134   Cu_51    Cu        2.6625        1.9377            3.7392
135   Cu_52    Cu        2.6625        1.9384            3.7155
136   Cu_53    Cu        2.6750        1.9353            3.7315
137   Cu_54    Cu        2.6875        1.9235            2.3799
138   Cu_55    Cu        2.6875        1.9243            3.0171
139   Cu_56    Cu        2.6875        1.9234            4.5669
140   Cu_57    Cu        2.6875        1.9224            4.1321
141   Cu_58    Cu        2.6875        1.9225            3.0570
142   Cu_59    Cu        2.6875        1.9231            3.0301
143   Cu_60    Cu        2.6875        1.9212            3.0438

In [1]:
import numpy as np
import pandas as pd

# =========================================================
# GEOMETRY + HX_NEAREST DESCRIPTOR EXTRACTION
# =========================================================
#
# Extracts:
#
# 1. M-M Distance
# 2. Shortest Intramolecular M-N Distance
# 3. Monomer Slippage
# 4. HX_nearest
#
# HX_nearest =
# shortest H---X distance in Py systems
#
# CN systems:
# HX_nearest = NaN
#
# =========================================================

coord_file = "All_Cu_Coordinates.txt"

# ---------------------------------------------------------
# READ FILE
# ---------------------------------------------------------

with open(coord_file, "r") as f:
    lines = f.readlines()

# ---------------------------------------------------------
# STORE COMPLEXES
# ---------------------------------------------------------

complexes = {}
current_complex = None

for line in lines:

    stripped = line.strip()

    if stripped.startswith("Complex"):

        current_complex = stripped.split(":")[1].strip()
        complexes[current_complex] = []

    elif stripped.startswith("=") or stripped == "":
        continue

    else:

        parts = stripped.split()

        if len(parts) == 4:

            atom = parts[0]

            x = float(parts[1])
            y = float(parts[2])
            z = float(parts[3])

            coord = np.array([x, y, z])

            complexes[current_complex].append(
                (atom, coord)
            )

# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------

def distance(a, b):
    return np.linalg.norm(a - b)

# ---------------------------------------------------------
# LIGAND IDENTIFICATION
# ---------------------------------------------------------

def identify_ligand(complex_name):

    metal, num = complex_name.split("_")
    num = int(num)

    if metal == "Ag":

        if num <= 28:
            return "CN"
        else:
            return "Py"

    elif metal == "Au":

        if num <= 70:
            return "CN"
        else:
            return "Py"

    elif metal == "Cu":

        if num <= 25:
            return "CN"
        else:
            return "Py"

    return None

# ---------------------------------------------------------
# RESULTS
# ---------------------------------------------------------

results = []

# ---------------------------------------------------------
# PROCESS EACH COMPLEX
# ---------------------------------------------------------

for complex_name, atoms in complexes.items():

    ligand_type = identify_ligand(complex_name)

    # -----------------------------------------------------
    # IDENTIFY METALS
    # -----------------------------------------------------

    metal_atoms = []

    for atom, coord in atoms:

        if atom in ["Cu", "Ag", "Au"]:

            metal_atoms.append(
                (atom, coord)
            )

    if len(metal_atoms) != 2:

        print(
            f"Skipping {complex_name} : metal issue"
        )
        continue

    metal_symbol = metal_atoms[0][0]

    M1 = metal_atoms[0][1]
    M2 = metal_atoms[1][1]

    # -----------------------------------------------------
    # M-M DISTANCE
    # -----------------------------------------------------

    MM_distance = distance(M1, M2)

    # -----------------------------------------------------
    # GEOMETRIC MONOMER ASSIGNMENT
    # -----------------------------------------------------

    monomer1 = []
    monomer2 = []

    for atom, coord in atoms:

        d1 = distance(coord, M1)
        d2 = distance(coord, M2)

        if d1 <= d2:

            monomer1.append(
                (atom, coord)
            )

        else:

            monomer2.append(
                (atom, coord)
            )

    # -----------------------------------------------------
    # SHORTEST M-N
    # -----------------------------------------------------

    N1_distances = []
    N2_distances = []

    for atom, coord in monomer1:

        if atom == "N":

            N1_distances.append(
                distance(M1, coord)
            )

    for atom, coord in monomer2:

        if atom == "N":

            N2_distances.append(
                distance(M2, coord)
            )

    if len(N1_distances) == 0 or len(N2_distances) == 0:

        print(
            f"Skipping {complex_name} : N issue"
        )
        continue

    shortest_MN = (
        min(N1_distances)
        + min(N2_distances)
    ) / 2

    # -----------------------------------------------------
    # HEAVY ATOM CENTROIDS
    # -----------------------------------------------------

    heavy_atoms_1 = [
        coord
        for atom, coord in monomer1
        if atom != "H"
    ]

    heavy_atoms_2 = [
        coord
        for atom, coord in monomer2
        if atom != "H"
    ]

    centroid1 = np.mean(
        heavy_atoms_1,
        axis=0
    )

    centroid2 = np.mean(
        heavy_atoms_2,
        axis=0
    )

    # -----------------------------------------------------
    # MONOMER SLIPPAGE
    # -----------------------------------------------------

    MM_axis = M2 - M1

    MM_unit = (
        MM_axis /
        np.linalg.norm(MM_axis)
    )

    centroid_vector = (
        centroid2 - centroid1
    )

    projection_length = np.dot(
        centroid_vector,
        MM_unit
    )

    projection_vector = (
        projection_length *
        MM_unit
    )

    perpendicular_vector = (
        centroid_vector -
        projection_vector
    )

    slippage = np.linalg.norm(
        perpendicular_vector
    )

    # -----------------------------------------------------
    # HX_NEAREST
    # -----------------------------------------------------

    HX_nearest = np.nan

    if ligand_type == "Py":

        H_atoms = []
        X_atoms = []

        for atom, coord in atoms:

            if atom == "H":
                H_atoms.append(coord)

            if atom in [
                "F",
                "Cl",
                "Br",
                "I"
            ]:
                X_atoms.append(coord)

        if (
            len(H_atoms) > 0
            and
            len(X_atoms) > 0
        ):

            all_distances = []

            for H in H_atoms:

                for X in X_atoms:

                    all_distances.append(
                        distance(H, X)
                    )

            HX_nearest = min(
                all_distances
            )

    # -----------------------------------------------------
    # STORE RESULTS
    # -----------------------------------------------------

    results.append({

        "Complex":
            complex_name,

        "Metal":
            metal_symbol,

        "Ligand":
            ligand_type,

        "M_M_Distance":
            round(
                MM_distance,
                4
            ),

        "Shortest_M_N":
            round(
                shortest_MN,
                4
            ),

        "Monomer_Slippage":
            round(
                slippage,
                4
            ),

        "HX_nearest":
            round(
                HX_nearest,
                4
            )
            if not pd.isna(
                HX_nearest
            )
            else np.nan

    })

# ---------------------------------------------------------
# DATAFRAME
# ---------------------------------------------------------

df = pd.DataFrame(results)

pd.set_option(
    "display.max_rows",
    None
)

pd.set_option(
    "display.max_columns",
    None
)

print(df)

# ---------------------------------------------------------
# HX SUMMARY
# ---------------------------------------------------------

print("\n")
print("=" * 60)
print("HX_nearest Summary")
print("=" * 60)

print(
    df["HX_nearest"]
    .describe()
)

# ---------------------------------------------------------
# SAVE
# ---------------------------------------------------------

df.to_csv(
    "Geometry_Descriptors_with_HX.csv",
    index=False
)

print("\nSaved:")
print(
    "Geometry_Descriptors_with_HX.csv"
)

    Complex Metal Ligand  M_M_Distance  Shortest_M_N  Monomer_Slippage  \
0      Ag_1    Ag     CN        3.0375        2.0693            1.0665
1      Ag_2    Ag     CN        3.0125        2.0885            2.1310
2      Ag_3    Ag     CN        3.0250        2.0650            4.0887
3      Ag_4    Ag     CN        3.0125        2.0594            2.1595
4      Ag_5    Ag     CN        3.0375        2.0685            2.1696
5      Ag_6    Ag     CN        3.0375        2.0690            2.1351
6      Ag_7    Ag     CN        3.0250        2.0795            1.0745
7      Ag_8    Ag     CN        3.0125        2.0866            1.0339
8      Ag_9    Ag     CN        2.9875        2.1056            2.1098
9     Ag_10    Ag     CN        3.0000        2.0829            4.0853
10    Ag_11    Ag     CN        3.0000        2.0768            2.1386
11    Ag_12    Ag     CN        3.0125        2.0834            2.1466
12    Ag_13    Ag     CN        3.0250        2.0833            2.1115
13    Ag_14    Ag     CN        3.0125        2.0945            1.0405
14    Ag_15    Ag     CN        3.0000        2.1108            0.9937
15    Ag_16    Ag     CN        2.9750        2.1298            2.0848
16    Ag_17    Ag     CN        2.9875        2.1089            4.0842
17    Ag_18    Ag     CN        2.9875        2.1007            2.1129
18    Ag_19    Ag     CN        3.0000        2.1051            2.1193
19    Ag_20    Ag     CN        3.0125        2.1037            2.0833
20    Ag_21    Ag     CN        3.0000        2.1163            0.9988
21    Ag_22    Ag     CN        3.0750        2.0834            0.0399
22    Ag_23    Ag     CN        3.0625        2.1087            1.1056
23    Ag_24    Ag     CN        3.0500        2.0827            3.1939
24    Ag_25    Ag     CN        3.0500        2.0822            1.1307
25    Ag_26    Ag     CN        3.0750        2.0787            1.1302
26    Ag_27    Ag     CN        3.0750        2.0769            1.1017
27    Ag_28    Ag     CN        3.0625        2.0874            0.0506
28    Ag_29    Ag     Py        2.9250        2.1300            3.3204
29    Ag_30    Ag     Py        2.9250        2.1296            3.9221
30    Ag_31    Ag     Py        2.9250        2.1334            5.4048
31    Ag_32    Ag     Py        2.9250        2.1343            3.9460
32    Ag_33    Ag     Py        2.9375        2.1287            3.9665
33    Ag_34    Ag     Py        2.9250        2.1253            3.9470
34    Ag_35    Ag     Py        2.9250        2.1294            3.3258
35    Ag_36    Ag     Py        2.9625        2.1348            2.5009
36    Ag_37    Ag     Py        2.9625        2.1366            3.1273
37    Ag_38    Ag     Py        2.9750        2.1379            4.6779
38    Ag_39    Ag     Py        2.9625        2.1408            3.1469
39    Ag_40    Ag     Py        2.9625        2.1303            3.1616
40    Ag_41    Ag     Py        2.9625        2.1264            3.1439
41    Ag_42    Ag     Py        2.9625        2.1318            2.5038
42    Au_43    Au     CN        3.1750        1.9632            1.0064
43    Au_44    Au     CN        3.1500        1.9859            2.0558
44    Au_45    Au     CN        3.1750        1.9547            3.9795
45    Au_46    Au     CN        3.1750        1.9492            2.0770
46    Au_47    Au     CN        3.1750        1.9712            2.0980
47    Au_48    Au     CN        3.1750        1.9772            2.0684
48    Au_49    Au     CN        3.1625        1.9839            1.0211
49    Au_50    Au     CN        3.1500        1.9785            0.9723
50    Au_51    Au     CN        3.1250        2.0021            2.0338
51    Au_52    Au     CN        3.1500        1.9703            3.9737
52    Au_53    Au     CN        3.1625        1.9642            2.0539
53    Au_54    Au     CN        3.1500        1.9856            2.0750
54    Au_55    Au     CN        3.1500        1.9911            2.0445
55    Au_56    Au     CN        3.1375        1.9987            0.9870
56    Au_57    Au     CN        3.1250        2.0036            0.9330
57    Au_58    Au     CN        3.0875        2.0290            2.0114
58    Au_59    Au     CN        3.1125        1.9956            3.9721
59    Au_60    Au     CN        3.1250        1.9883            2.0287
60    Au_61    Au     CN        3.1250        2.0093            2.0498
61    Au_62    Au     CN        3.1250        2.0140            2.0189
62    Au_63    Au     CN        3.1125        2.0233            0.9480
63    Au_64    Au     CN        3.1625        2.0025            0.0288
64    Au_65    Au     CN        3.1500        2.0224            1.0745
65    Au_66    Au     CN        3.1625        1.9967            3.1318
66    Au_67    Au     CN        3.1500        1.9925            1.0954
67    Au_68    Au     CN        3.1625        2.0069            1.1096
68    Au_69    Au     CN        3.1750        2.0102            1.0834
69    Au_70    Au     CN        3.1625        2.0177            0.0430
70    Au_71    Au     Py        3.0625        2.0455            3.2356
71    Au_72    Au     Py        3.0750        2.0484            3.8367
72    Au_73    Au     Py        3.0625        2.0443            5.3023
73    Au_74    Au     Py        3.0750        2.0418            3.8484
74    Au_75    Au     Py        3.0625        2.0452            3.8782
75    Au_76    Au     Py        3.0625        2.0459            3.8619
76    Au_77    Au     Py        3.0625        2.0471            3.2424
77    Au_78    Au     Py        3.0625        2.0471            3.2424
78    Au_79    Au     Py        3.0750        2.0762            3.0816
79    Au_80    Au     Py        3.0750        2.0750            4.6192
80    Au_81    Au     Py        3.0750        2.0746            3.0960
81    Au_82    Au     Py        3.0625        2.0724            3.1185
82    Au_83    Au     Py        3.0750        2.0711            3.1025
83    Au_84    Au     Py        3.1250        2.0741            3.0936
84     Cu_1    Cu     CN        2.6625        1.8068            1.0304
85     Cu_2    Cu     CN        2.6375        1.8241            2.0924
86     Cu_3    Cu     CN        2.6500        1.7995            3.8067
87     Cu_4    Cu     CN        2.6500        1.7949            3.3631
88     Cu_5    Cu     CN        2.7250        1.7922            2.2019
89     Cu_6    Cu     CN        2.7000        1.8435            1.0250
90     Cu_7    Cu     CN        2.7000        1.8609            2.1403
91     Cu_8    Cu     CN        2.7125        1.8358            4.0787
92     Cu_9    Cu     CN        2.7000        1.8304            3.5863
93    Cu_10    Cu     CN        2.7000        1.8221            2.1492
94    Cu_11    Cu     CN        2.7000        1.8536            0.9665
95    Cu_12    Cu     CN        2.6875        1.8719            2.1252
96    Cu_13    Cu     CN        2.7000        1.8470            4.0903
97    Cu_14    Cu     CN        2.6875        1.8414            3.5932
98    Cu_15    Cu     CN        2.7000        1.8310            2.1322
99    Cu_16    Cu     CN        2.6875        1.8690            0.9184
100   Cu_17    Cu     CN        2.6750        1.8883            2.1086
101   Cu_18    Cu     CN        2.6875        1.8627            4.1050
102   Cu_19    Cu     CN        2.6625        1.8568            3.5979
103   Cu_20    Cu     CN        2.6875        1.8462            2.1150
104   Cu_21    Cu     CN        2.7000        1.8601            0.0122
105   Cu_22    Cu     CN        2.7000        1.8748            1.1170
106   Cu_23    Cu     CN        2.7125        1.8546            3.1733
107   Cu_24    Cu     CN        2.6875        1.8502            2.6412
108   Cu_25    Cu     CN        2.6500        1.8412            1.1754
109   Cu_26    Cu     Py        2.7375        1.8856            3.2098
110   Cu_27    Cu     Py        2.7375        1.8871            3.8205
111   Cu_28    Cu     Py        2.7250        1.8836            3.7512
112   Cu_29    Cu     Py        2.7000        1.8809            4.9148
113   Cu_30    Cu     Py        2.7500        1.8857            3.8480
114   Cu_31    Cu     Py        2.7625        1.8877            3.8069
115   Cu_32    Cu     Py        2.7750        1.8885            3.9177
116   Cu_33    Cu     Py        2.7125        1.9167            3.1609
117   Cu_34    Cu     Py        2.7125        1.9183            3.7756
118   Cu_35    Cu     Py        2.7125        1.9160            5.2439
119   Cu_36    Cu     Py        2.7000        1.9145            4.8464
120   Cu_37    Cu     Py        2.7125        1.9161            3.8165
121   Cu_38    Cu     Py        2.7250        1.9172            3.7822
122   Cu_39    Cu     Py        2.7250        1.9155            3.7978
123   Cu_40    Cu     Py        2.6875        1.9257            3.1352
124   Cu_41    Cu     Py        2.6875        1.9274            3.7479
125   Cu_42    Cu     Py        2.7250        1.9304            5.2477
126   Cu_43    Cu     Py        2.6875        1.9241            4.8098
127   Cu_44    Cu     Py        2.6875        1.9248            3.7895
128   Cu_45    Cu     Py        2.7000        1.9255            3.7576
129   Cu_46    Cu     Py        2.7000        1.9234            3.7797
130   Cu_47    Cu     Py        2.6625        1.9390            3.0904
131   Cu_48    Cu     Py        2.6625        1.9409            3.6937
132   Cu_49    Cu     Py        2.6625        1.9397            5.1477
133   Cu_50    Cu     Py        2.6625        1.9386            4.7453
134   Cu_51    Cu     Py        2.6625        1.9377            3.7392
135   Cu_52    Cu     Py        2.6625        1.9384            3.7155
136   Cu_53    Cu     Py        2.6750        1.9353            3.7315
137   Cu_54    Cu     Py        2.6875        1.9235            2.3799
138   Cu_55    Cu     Py        2.6875        1.9243            3.0171
139   Cu_56    Cu     Py        2.6875        1.9234            4.5669
140   Cu_57    Cu     Py        2.6875        1.9224            4.1321
141   Cu_58    Cu     Py        2.6875        1.9225            3.0570
142   Cu_59    Cu     Py        2.6875        1.9231            3.0301
143   Cu_60    Cu     Py        2.6875        1.9212            3.0438

     HX_nearest
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28       3.6755
29       2.6042
30       2.5029
31       3.6920
32       3.7471
33       3.7056
34       3.6853
35          NaN
36       2.6031
37       2.5020
38          NaN
39          NaN
40          NaN
41          NaN
42          NaN
43          NaN
44          NaN
45          NaN
46          NaN
47          NaN
48          NaN
49          NaN
50          NaN
51          NaN
52          NaN
53          NaN
54          NaN
55          NaN
56          NaN
57          NaN
58          NaN
59          NaN
60          NaN
61          NaN
62          NaN
63          NaN
64          NaN
65          NaN
66          NaN
67          NaN
68          NaN
69          NaN
70       3.7238
71       2.6050
72       2.5039
73       3.7537
74       3.7373
75       3.7442
76       3.7282
77       3.7282
78       2.6036
79       2.5017
80          NaN
81          NaN
82          NaN
83          NaN
84          NaN
85          NaN
86          NaN
87          NaN
88          NaN
89          NaN
90          NaN
91          NaN
92          NaN
93          NaN
94          NaN
95          NaN
96          NaN
97          NaN
98          NaN
99          NaN
100         NaN
101         NaN
102         NaN
103         NaN
104         NaN
105         NaN
106         NaN
107         NaN
108         NaN
109      2.2013
110      2.1774
111      2.1751
112      2.1682
113      2.2112
114      2.1884
115      2.2624
116      2.5822
117      2.5627
118      2.4787
119      2.5590
120      2.5853
121      2.5668
122      2.5842
123      2.7092
124      2.6023
125      2.4942
126      2.6905
127      2.7134
128      2.6968
129      2.7092
130      2.8993
131      2.6025
132      2.4736
133      2.8838
134      2.9035
135      2.8871
136      2.9006
137         NaN
138      2.6006
139      2.4587
140         NaN
141         NaN
142         NaN
143         NaN


============================================================
HX_nearest Summary
============================================================
count    49.000000
mean      2.813786
std       0.526411
min       2.168200
25%       2.502000
50%       2.603100
75%       2.900600
max       3.753700
Name: HX_nearest, dtype: float64

Saved:
Geometry_Descriptors_with_HX.csv

In [2]:
df[
    ["Complex",
     "Ligand",
     "HX_nearest"]
].head(20)

   Complex Ligand  HX_nearest
0     Ag_1     CN         NaN
1     Ag_2     CN         NaN
2     Ag_3     CN         NaN
3     Ag_4     CN         NaN
4     Ag_5     CN         NaN
5     Ag_6     CN         NaN
6     Ag_7     CN         NaN
7     Ag_8     CN         NaN
8     Ag_9     CN         NaN
9    Ag_10     CN         NaN
10   Ag_11     CN         NaN
11   Ag_12     CN         NaN
12   Ag_13     CN         NaN
13   Ag_14     CN         NaN
14   Ag_15     CN         NaN
15   Ag_16     CN         NaN
16   Ag_17     CN         NaN
17   Ag_18     CN         NaN
18   Ag_19     CN         NaN
19   Ag_20     CN         NaN

In [3]:
df["HX_nearest"].describe()

count    49.000000
mean      2.813786
std       0.526411
min       2.168200
25%       2.502000
50%       2.603100
75%       2.900600
max       3.753700
Name: HX_nearest, dtype: float64

In [4]:
df.sort_values(
    "HX_nearest"
)[
    ["Complex",
     "Ligand",
     "HX_nearest"]
].head(20)

    Complex Ligand  HX_nearest
112   Cu_29     Py      2.1682
111   Cu_28     Py      2.1751
110   Cu_27     Py      2.1774
114   Cu_31     Py      2.1884
109   Cu_26     Py      2.2013
113   Cu_30     Py      2.2112
115   Cu_32     Py      2.2624
139   Cu_56     Py      2.4587
132   Cu_49     Py      2.4736
118   Cu_35     Py      2.4787
125   Cu_42     Py      2.4942
79    Au_80     Py      2.5017
37    Ag_38     Py      2.5020
30    Ag_31     Py      2.5029
72    Au_73     Py      2.5039
119   Cu_36     Py      2.5590
117   Cu_34     Py      2.5627
121   Cu_38     Py      2.5668
116   Cu_33     Py      2.5822
122   Cu_39     Py      2.5842

In [5]:
df.sort_values(
    "HX_nearest",
    ascending=False
)[
    ["Complex",
     "Ligand",
     "HX_nearest"]
].head(20)

    Complex Ligand  HX_nearest
73    Au_74     Py      3.7537
32    Ag_33     Py      3.7471
75    Au_76     Py      3.7442
74    Au_75     Py      3.7373
77    Au_78     Py      3.7282
76    Au_77     Py      3.7282
70    Au_71     Py      3.7238
33    Ag_34     Py      3.7056
31    Ag_32     Py      3.6920
34    Ag_35     Py      3.6853
28    Ag_29     Py      3.6755
134   Cu_51     Py      2.9035
136   Cu_53     Py      2.9006
130   Cu_47     Py      2.8993
135   Cu_52     Py      2.8871
133   Cu_50     Py      2.8838
127   Cu_44     Py      2.7134
129   Cu_46     Py      2.7092
123   Cu_40     Py      2.7092
128   Cu_45     Py      2.6968

In [7]:
import pandas as pd

# Geometry descriptor file
geom_df = pd.read_csv(
    "Geometry_Descriptors.csv"
)

# Original dataset containing E
data_df = pd.read_csv(
    "updated_metallophilic_dataset.csv"
)

# Check common identifier column
print(geom_df.columns)
print(data_df.columns)

Index(['Complex', 'Metal', 'Ligand', 'M_M_Distance', 'Shortest_M_N',
       'Monomer_Slippage', 'HX_nearest'],
      dtype='object')
Index(['dimer', 'Metal', 'Ligand', 'X', 'R', 'Y_Smiles', 'E', 'd', 'rho',
       'laplacian', 'V', 'G', 'V_over_G'],
      dtype='object')

In [8]:
merged_df = geom_df.merge(
    data_df[['dimer', 'E']],
    left_on='Complex',
    right_on='dimer',
    how='left'
)

print(merged_df.head())

  Complex Metal Ligand  M_M_Distance  Shortest_M_N  Monomer_Slippage  \
0    Ag_1    Ag     CN        3.0375        2.0693            1.0665
1    Ag_2    Ag     CN        3.0125        2.0885            2.1310
2    Ag_3    Ag     CN        3.0250        2.0650            4.0887
3    Ag_4    Ag     CN        3.0125        2.0594            2.1595
4    Ag_5    Ag     CN        3.0375        2.0685            2.1696

   HX_nearest dimer     E
0         NaN  Ag_1 -6.16
1         NaN  Ag_2 -6.57
2         NaN  Ag_3 -6.67
3         NaN  Ag_4 -6.58
4         NaN  Ag_5 -6.00

In [9]:
cols = [
    'HX_nearest',
    'M_M_Distance',
    'Shortest_M_N',
    'Monomer_Slippage',
    'E'
]

print(
    merged_df[cols].corr()
)

                  HX_nearest  M_M_Distance  Shortest_M_N  Monomer_Slippage  \
HX_nearest          1.000000      0.555368      0.613210         -0.304950
M_M_Distance        0.555368      1.000000      0.698573         -0.382420
Shortest_M_N        0.613210      0.698573      1.000000         -0.108725
Monomer_Slippage   -0.304950     -0.382420     -0.108725          1.000000
E                   0.572802      0.748988      0.348180         -0.625675

                         E
HX_nearest        0.572802
M_M_Distance      0.748988
Shortest_M_N      0.348180
Monomer_Slippage -0.625675
E                 1.000000

In [10]:
py_df = merged_df[
    merged_df['Ligand'] == 'Py'
]

print(
    py_df[cols].corr()
)

                  HX_nearest  M_M_Distance  Shortest_M_N  Monomer_Slippage  \
HX_nearest          1.000000      0.555368      0.613210         -0.304950
M_M_Distance        0.555368      1.000000      0.821304         -0.183980
Shortest_M_N        0.613210      0.821304      1.000000         -0.190081
Monomer_Slippage   -0.304950     -0.183980     -0.190081          1.000000
E                   0.572802      0.933732      0.811154         -0.277644

                         E
HX_nearest        0.572802
M_M_Distance      0.933732
Shortest_M_N      0.811154
Monomer_Slippage -0.277644
E                 1.000000