In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

from xgboost import XGBRegressor

import matplotlib.pyplot as plt

import shap

Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)

In [4]:
df = pd.read_csv(
    "Reduced_Metallophilic_Dataset.csv"
)

print(df.shape)

df["HX_nearest"] = (
    df["HX_nearest"]
    .fillna(0)
)
hammett_map = {

    "NH2": -0.66,
    "OH" : -0.37,
    "CH3": -0.17,

    "H"  : 0.00,

    "F"  : 0.06,

    "CF3": 0.54,
    "NO2": 0.78
}

df["Hammett_sigma"] = (
    df["R"]
    .map(hammett_map)
)

(144, 36)

In [5]:
cu_sets = {

    "Set_1": [1,7,13,19,25,31,37,43,49,55],

    "Set_2": [2,8,14,20,26,32,38,44,50,56],

    "Set_3": [3,9,15,21,27,33,39,45,51,57],

    "Set_4": [4,10,16,22,28,34,40,46,52,58],

    "Set_5": [5,11,17,23,29,35,41,47,53,59],

    "Set_6": [6,12,18,24,30,36,42,48,54,60]
}

In [6]:
xgb_params = {

    "n_estimators": 200,

    "learning_rate": 0.05,

    "max_depth": 4,

    "random_state": 42
}

In [7]:
# =========================================================
# TARGET
# =========================================================

target_column = 'E'

y = df[target_column]

print(y.shape)
# =========================================================
# QTAIM DESCRIPTORS
# =========================================================

qtaim_columns = [

    'rho',
    'laplacian',
    'V',
    'G',
    'V_over_G'

]


# =========================================================
# GEOMETRY DESCRIPTORS
# =========================================================

geometry_columns = [

    'd',
    'Shortest_M_N',
    'Monomer_Slippage',
    'HX_nearest'

]


# =========================================================
# QM DESCRIPTORS
# =========================================================

qm_columns = (

    qtaim_columns +

    geometry_columns

)


# =========================================================
# ML DESCRIPTORS
# =========================================================

ml_columns = [

    'Metal_atomic_number',
    'Metal_atomic_radius',
    'Metal_electronegativity',
    'Metal_polarizability',
    'Metal_ionization_energy',

    'X_atomic_number',
    'X_atomic_radius',
    'X_electronegativity',
    'X_polarizability',
    'X_ionization_energy',
    
    'nAromAtom',
    'nN',
    'nO',
    'nF',
    'nAtom',
    'Hammett_sigma'

]

# =========================================================
# FULL DESCRIPTOR SET
# =========================================================

full_columns = ( qm_columns + ml_columns )

(144,)

In [8]:
descriptor_sets = {

    "QM":
        qm_columns,

    "ML":
        ml_columns,

    "FULL":
        full_columns
}

In [9]:
def prepare_features(
    train_df,
    test_df,
    columns
):

    scaler = StandardScaler()

    X_train = pd.DataFrame(

        scaler.fit_transform(
            train_df[columns]
        ),

        columns=columns,
        index=train_df.index
    )

    X_test = pd.DataFrame(

        scaler.transform(
            test_df[columns]
        ),

        columns=columns,
        index=test_df.index
    )

    return (
        X_train,
        X_test
    )

In [10]:
# =========================================================
# VALIDATION FUNCTION
# =========================================================

def run_validation(
    df,
    columns,
    test_set,
    xgb_params
):

    # -----------------------------------------------------
    # DEFINE TEST DIMERS
    # -----------------------------------------------------

    test_dimers = [

        f"Cu_{i}"

        for i in test_set

    ]

    # -----------------------------------------------------
    # TRAIN / TEST SPLIT
    # -----------------------------------------------------

    test_df = df[
        df["dimer"].isin(
            test_dimers
        )
    ].copy()

    train_df = df[
        ~df["dimer"].isin(
            test_dimers
        )
    ].copy()

    # -----------------------------------------------------
    # FEATURES
    # -----------------------------------------------------

    X_train, X_test = prepare_features(

        train_df,
        test_df,
        columns

    )

    # -----------------------------------------------------
    # TARGET
    # -----------------------------------------------------

    y_train = train_df["E"]

    y_test = test_df["E"]

    # -----------------------------------------------------
    # MODEL
    # -----------------------------------------------------

    model = XGBRegressor(

        **xgb_params

    )

    # -----------------------------------------------------
    # TRAIN MODEL
    # -----------------------------------------------------

    model.fit(

        X_train,
        y_train

    )

    # -----------------------------------------------------
    # PREDICTIONS
    # -----------------------------------------------------

    y_pred = model.predict(

        X_test

    )

    # -----------------------------------------------------
    # METRICS
    # -----------------------------------------------------

    mae = mean_absolute_error(

        y_test,
        y_pred

    )

    rmse = np.sqrt(

        mean_squared_error(

            y_test,
            y_pred

        )

    )

    r2 = r2_score(

        y_test,
        y_pred

    )

    # -----------------------------------------------------
    # PREDICTION TABLE
    # -----------------------------------------------------

    prediction_df = pd.DataFrame({

        "Dimer":
            test_df["dimer"].values,

        "Actual_E":
            y_test.values,

        "Predicted_E":
            y_pred

    })

    prediction_df["Error"] = (

        prediction_df["Actual_E"]

        -

        prediction_df["Predicted_E"]

    )

    prediction_df["Abs_Error"] = (

        prediction_df["Error"]

        .abs()

    )

    # -----------------------------------------------------
    # RETURN RESULTS
    # -----------------------------------------------------

    return {

        "MAE":
            mae,

        "RMSE":
            rmse,

        "R2":
            r2,

        "Train_Size":
            len(train_df),

        "Test_Size":
            len(test_df),

        "Model":
            model,

        "Predictions":
            prediction_df

    }

In [11]:
test_result = run_validation(

    df,

    ml_columns,

    cu_sets["Set_1"],

    xgb_params

)

print(

    test_result["MAE"],
    test_result["RMSE"],
    test_result["R2"]

)

test_result["Predictions"].head()

0.20391717720031774 0.28956571913768087 0.9957459002689131

   Dimer  Actual_E  Predicted_E     Error  Abs_Error
0   Cu_1     -6.64    -7.381104  0.741104   0.741104
1   Cu_7     -8.70    -8.932101  0.232101   0.232101
2  Cu_13     -9.13    -9.139941  0.009941   0.009941
3  Cu_19    -10.32   -10.148756 -0.171244   0.171244
4  Cu_25     -6.28    -6.281965  0.001965   0.001965

In [12]:
# =========================================================
# RUN ALL VALIDATION TESTS
# =========================================================

summary_rows = []

all_prediction_tables = {}

for descriptor_name, columns in descriptor_sets.items():

    descriptor_predictions = []

    print("\n")
    print("=" * 60)
    print(f"{descriptor_name} VALIDATION")
    print("=" * 60)

    for set_name, test_set in cu_sets.items():

        results = run_validation(

            df=df,

            columns=columns,

            test_set=test_set,

            xgb_params=xgb_params

        )

        # ---------------------------------------------
        # SUMMARY TABLE
        # ---------------------------------------------

        summary_rows.append({

            "Descriptor_Set":
                descriptor_name,

            "Test_Set":
                set_name,

            "Train_Size":
                results["Train_Size"],

            "Test_Size":
                results["Test_Size"],

            "MAE":
                results["MAE"],

            "RMSE":
                results["RMSE"],

            "R2":
                results["R2"]

        })

        # ---------------------------------------------
        # PREDICTION TABLE
        # ---------------------------------------------

        prediction_df = (

            results["Predictions"]

            .copy()

        )

        prediction_df["Descriptor_Set"] = (
            descriptor_name
        )

        prediction_df["Test_Set"] = (
            set_name
        )

        descriptor_predictions.append(
            prediction_df
        )

        # ---------------------------------------------
        # PRINT RESULTS
        # ---------------------------------------------

        print(
            f"{set_name:6s}"
            f" | MAE = {results['MAE']:.4f}"
            f" | RMSE = {results['RMSE']:.4f}"
            f" | R² = {results['R2']:.4f}"
        )

    # -------------------------------------------------
    # COMBINE ALL SIX SETS
    # -------------------------------------------------

    all_prediction_tables[
        descriptor_name
    ] = pd.concat(

        descriptor_predictions,

        ignore_index=True

    )

============================================================
QM VALIDATION
============================================================
Set_1  | MAE = 0.8172 | RMSE = 1.1644 | R² = 0.9312
Set_2  | MAE = 0.6582 | RMSE = 0.7350 | R² = 0.9615
Set_3  | MAE = 0.6415 | RMSE = 0.7303 | R² = 0.9687
Set_4  | MAE = 0.5468 | RMSE = 0.5984 | R² = 0.9785
Set_5  | MAE = 1.1694 | RMSE = 1.8740 | R² = 0.8190
Set_6  | MAE = 0.7856 | RMSE = 1.5415 | R² = 0.8205


============================================================
ML VALIDATION
============================================================
Set_1  | MAE = 0.2039 | RMSE = 0.2896 | R² = 0.9957
Set_2  | MAE = 0.2314 | RMSE = 0.3352 | R² = 0.9920
Set_3  | MAE = 0.1686 | RMSE = 0.2140 | R² = 0.9973
Set_4  | MAE = 0.1716 | RMSE = 0.2222 | R² = 0.9970
Set_5  | MAE = 0.2223 | RMSE = 0.2856 | R² = 0.9958
Set_6  | MAE = 0.2465 | RMSE = 0.3393 | R² = 0.9913


============================================================
FULL VALIDATION
============================================================
Set_1  | MAE = 0.6982 | RMSE = 1.1054 | R² = 0.9380
Set_2  | MAE = 0.3046 | RMSE = 0.4391 | R² = 0.9863
Set_3  | MAE = 0.3186 | RMSE = 0.3837 | R² = 0.9914
Set_4  | MAE = 0.2331 | RMSE = 0.2910 | R² = 0.9949
Set_5  | MAE = 1.0336 | RMSE = 1.8941 | R² = 0.8151
Set_6  | MAE = 0.2021 | RMSE = 0.2619 | R² = 0.9948

In [13]:
# =========================================================
# VALIDATION SUMMARY
# =========================================================

validation_summary = pd.DataFrame(
    summary_rows
)

validation_summary

,Descriptor_Set,Test_Set,Train_Size,Test_Size,MAE,RMSE,R2
0,QM,Set_1,134,10,0.817183,1.164395,0.931212
1,QM,Set_2,134,10,0.658237,0.735030,0.961548
2,QM,Set_3,134,10,0.641503,0.730283,0.968727
3,QM,Set_4,134,10,0.546792,0.598415,0.978456
4,QM,Set_5,134,10,1.169416,1.873992,0.819034
5,QM,Set_6,134,10,0.785594,1.541524,0.820512
6,ML,Set_1,134,10,0.203917,0.289566,0.995746
7,ML,Set_2,134,10,0.231391,0.335237,0.992001
8,ML,Set_3,134,10,0.168643,0.213966,0.997315
9,ML,Set_4,134,10,0.171596,0.222211,0.997029
10,ML,Set_5,134,10,0.222307,0.285597,0.995797
11,ML,Set_6,134,10,0.246527,0.339322,0.991303
12,FULL,Set_1,134,10,0.698239,1.105388,0.938007
13,FULL,Set_2,134,10,0.304606,0.439139,0.986275
14,FULL,Set_3,134,10,0.318589,0.383666,0.991368
15,FULL,Set_4,134,10,0.233117,0.291027,0.994904
16,FULL,Set_5,134,10,1.033571,1.894131,0.815124
17,FULL,Set_6,134,10,0.202150,0.261873,0.994820

In [14]:
validation_summary.groupby(
    "Descriptor_Set"
)[
    ["MAE", "RMSE", "R2"]
].mean()

                     MAE      RMSE        R2
Descriptor_Set
FULL            0.465045  0.729204  0.953416
ML              0.207397  0.280983  0.994865
QM              0.769788  1.107273  0.913248

In [15]:
validation_summary

all_prediction_tables["QM"]

    Dimer  Actual_E  Predicted_E     Error  Abs_Error Descriptor_Set Test_Set
0    Cu_1     -6.64    -8.113832  1.473832   1.473832             QM    Set_1
1    Cu_7     -8.70    -8.808965  0.108965   0.108965             QM    Set_1
2   Cu_13     -9.13    -9.174754  0.044754   0.044754             QM    Set_1
3   Cu_19    -10.32    -8.530622 -1.789378   1.789378             QM    Set_1
4   Cu_25     -6.28    -8.924335  2.644335   2.644335             QM    Set_1
5   Cu_31    -17.17   -16.282015 -0.887985   0.887985             QM    Set_1
6   Cu_37    -15.90   -16.307186  0.407186   0.407186             QM    Set_1
7   Cu_43    -17.41   -17.116142 -0.293858   0.293858             QM    Set_1
8   Cu_49    -17.14   -17.423744  0.283744   0.283744             QM    Set_1
9   Cu_55    -16.31   -16.072203 -0.237797   0.237797             QM    Set_1
10   Cu_2     -8.08    -7.453662 -0.626338   0.626338             QM    Set_2
11   Cu_8     -8.66    -9.060805  0.400805   0.400805             QM    Set_2
12  Cu_14     -9.52    -8.912842 -0.607158   0.607158             QM    Set_2
13  Cu_20     -9.33    -7.994192 -1.335808   1.335808             QM    Set_2
14  Cu_26    -16.40   -15.828003 -0.571997   0.571997             QM    Set_2
15  Cu_32    -15.37   -16.567230  1.197230   1.197230             QM    Set_2
16  Cu_38    -17.01   -16.485804 -0.524196   0.524196             QM    Set_2
17  Cu_44    -15.98   -16.189163  0.209163   0.209163             QM    Set_2
18  Cu_50    -17.28   -16.756414 -0.523586   0.523586             QM    Set_2
19  Cu_56    -16.64   -17.226091  0.586091   0.586091             QM    Set_2
20   Cu_3     -7.94    -8.532995  0.592995   0.592995             QM    Set_3
21   Cu_9     -9.18    -8.332651 -0.847349   0.847349             QM    Set_3
22  Cu_15     -8.08    -7.670067 -0.409933   0.409933             QM    Set_3
23  Cu_21     -7.46    -8.359224  0.899224   0.899224             QM    Set_3
24  Cu_27    -17.36   -16.759129 -0.600871   0.600871             QM    Set_3
25  Cu_33    -16.31   -15.898701 -0.411299   0.411299             QM    Set_3
26  Cu_39    -15.66   -16.867884  1.207884   1.207884             QM    Set_3
27  Cu_45    -16.92   -16.651413 -0.268587   0.268587             QM    Set_3
28  Cu_51    -15.90   -15.972220  0.072220   0.072220             QM    Set_3
29  Cu_57    -16.86   -15.755336 -1.104664   1.104664             QM    Set_3
30   Cu_4     -8.30    -7.964164 -0.335836   0.335836             QM    Set_4
31  Cu_10     -7.51    -8.031857  0.521857   0.521857             QM    Set_4
32  Cu_16     -9.17    -8.481067 -0.688933   0.688933             QM    Set_4
33  Cu_22     -7.97    -8.413394  0.443394   0.443394             QM    Set_4
34  Cu_28    -17.49   -16.893549 -0.596451   0.596451             QM    Set_4
35  Cu_34    -17.13   -16.721067 -0.408933   0.408933             QM    Set_4
36  Cu_40    -16.22   -16.056868 -0.163132   0.163132             QM    Set_4
37  Cu_46    -15.47   -16.597792  1.127792   1.127792             QM    Set_4
38  Cu_52    -16.90   -16.359558 -0.540442   0.540442             QM    Set_4
39  Cu_58    -15.31   -15.951154  0.641154   0.641154             QM    Set_4
40   Cu_5     -5.45    -7.714207  2.264207   2.264207             QM    Set_5
41  Cu_11     -8.37    -8.734803  0.364803   0.364803             QM    Set_5
42  Cu_17    -10.20   -15.283049  5.083049   5.083049             QM    Set_5
43  Cu_23     -8.05    -9.622420  1.572420   1.572420             QM    Set_5
44  Cu_29    -17.65   -17.430695 -0.219305   0.219305             QM    Set_5
45  Cu_35    -17.29   -17.072475 -0.217525   0.217525             QM    Set_5
46  Cu_41    -17.02   -16.754162 -0.265838   0.265838             QM    Set_5
47  Cu_47    -16.11   -15.975450 -0.134550   0.134550             QM    Set_5
48  Cu_53    -15.60   -16.132891  0.532891   0.532891             QM    Set_5
49  Cu_59    -16.33   -15.290433 -1.039567   1.039567             QM    Set_5
50   Cu_6     -8.58    -8.452703 -0.127297   0.127297             QM    Set_6
51  Cu_12     -9.24    -9.339393  0.099393   0.099393             QM    Set_6
52  Cu_18     -9.82    -9.453911 -0.366089   0.366089             QM    Set_6
53  Cu_24     -8.68    -8.418826 -0.261174   0.261174             QM    Set_6
54  Cu_30    -16.12   -16.924522  0.804522   0.804522             QM    Set_6
55  Cu_36    -17.42   -17.412893 -0.007107   0.007107             QM    Set_6
56  Cu_42    -17.03   -17.262175  0.232175   0.232175             QM    Set_6
57  Cu_48    -16.98   -16.729126 -0.250874   0.250874             QM    Set_6
58  Cu_54    -15.61   -10.955818 -4.654182   4.654182             QM    Set_6
59  Cu_60    -14.93   -15.983129  1.053129   1.053129             QM    Set_6

In [16]:
all_prediction_tables["ML"]

    Dimer  Actual_E  Predicted_E     Error  Abs_Error Descriptor_Set Test_Set
0    Cu_1     -6.64    -7.381104  0.741104   0.741104             ML    Set_1
1    Cu_7     -8.70    -8.932101  0.232101   0.232101             ML    Set_1
2   Cu_13     -9.13    -9.139941  0.009941   0.009941             ML    Set_1
3   Cu_19    -10.32   -10.148756 -0.171244   0.171244             ML    Set_1
4   Cu_25     -6.28    -6.281965  0.001965   0.001965             ML    Set_1
5   Cu_31    -17.17   -16.819092 -0.350908   0.350908             ML    Set_1
6   Cu_37    -15.90   -16.079601  0.179601   0.179601             ML    Set_1
7   Cu_43    -17.41   -17.290630 -0.119370   0.119370             ML    Set_1
8   Cu_49    -17.14   -17.091272 -0.048728   0.048728             ML    Set_1
9   Cu_55    -16.31   -16.494209  0.184209   0.184209             ML    Set_1
10   Cu_2     -8.08    -7.950998 -0.129002   0.129002             ML    Set_2
11   Cu_8     -8.66    -8.915401  0.255401   0.255401             ML    Set_2
12  Cu_14     -9.52    -9.505668 -0.014332   0.014332             ML    Set_2
13  Cu_20     -9.33    -8.559894 -0.770106   0.770106             ML    Set_2
14  Cu_26    -16.40   -16.391123 -0.008877   0.008877             ML    Set_2
15  Cu_32    -15.37   -15.628100  0.258100   0.258100             ML    Set_2
16  Cu_38    -17.01   -16.823769 -0.186231   0.186231             ML    Set_2
17  Cu_44    -15.98   -16.009394  0.029394   0.029394             ML    Set_2
18  Cu_50    -17.28   -17.359213  0.079213   0.079213             ML    Set_2
19  Cu_56    -16.64   -16.056749 -0.583251   0.583251             ML    Set_2
20   Cu_3     -7.94    -8.003418  0.063418   0.063418             ML    Set_3
21   Cu_9     -9.18    -9.124717 -0.055283   0.055283             ML    Set_3
22  Cu_15     -8.08    -8.359941  0.279941   0.279941             ML    Set_3
23  Cu_21     -7.46    -7.020265 -0.439735   0.439735             ML    Set_3
24  Cu_27    -17.36   -17.207930 -0.152070   0.152070             ML    Set_3
25  Cu_33    -16.31   -16.290216 -0.019784   0.019784             ML    Set_3
26  Cu_39    -15.66   -15.434120 -0.225880   0.225880             ML    Set_3
27  Cu_45    -16.92   -16.916931 -0.003069   0.003069             ML    Set_3
28  Cu_51    -15.90   -16.076519  0.176519   0.176519             ML    Set_3
29  Cu_57    -16.86   -16.589266 -0.270734   0.270734             ML    Set_3
30   Cu_4     -8.30    -8.353135  0.053135   0.053135             ML    Set_4
31  Cu_10     -7.51    -7.935570  0.425570   0.425570             ML    Set_4
32  Cu_16     -9.17    -9.335709  0.165709   0.165709             ML    Set_4
33  Cu_22     -7.97    -8.045793  0.075793   0.075793             ML    Set_4
34  Cu_28    -17.49   -17.153927 -0.336073   0.336073             ML    Set_4
35  Cu_34    -17.13   -17.039276 -0.090724   0.090724             ML    Set_4
36  Cu_40    -16.22   -16.215771 -0.004229   0.004229             ML    Set_4
37  Cu_46    -15.47   -15.484499  0.014499   0.014499             ML    Set_4
38  Cu_52    -16.90   -16.668825 -0.231175   0.231175             ML    Set_4
39  Cu_58    -15.31   -15.629050  0.319050   0.319050             ML    Set_4
40   Cu_5     -5.45    -5.903555  0.453555   0.453555             ML    Set_5
41  Cu_11     -8.37    -8.642581  0.272581   0.272581             ML    Set_5
42  Cu_17    -10.20    -9.628292 -0.571708   0.571708             ML    Set_5
43  Cu_23     -8.05    -7.987858 -0.062142   0.062142             ML    Set_5
44  Cu_29    -17.65   -17.275614 -0.374386   0.374386             ML    Set_5
45  Cu_35    -17.29   -17.167238 -0.122762   0.122762             ML    Set_5
46  Cu_41    -17.02   -16.987144 -0.032856   0.032856             ML    Set_5
47  Cu_47    -16.11   -16.266722  0.156722   0.156722             ML    Set_5
48  Cu_53    -15.60   -15.446603 -0.153397   0.153397             ML    Set_5
49  Cu_59    -16.33   -16.352959  0.022959   0.022959             ML    Set_5
50   Cu_6     -8.58    -7.716536 -0.863464   0.863464             ML    Set_6
51  Cu_12     -9.24    -9.078227 -0.161773   0.161773             ML    Set_6
52  Cu_18     -9.82   -10.014867  0.194867   0.194867             ML    Set_6
53  Cu_24     -8.68    -8.347140 -0.332860   0.332860             ML    Set_6
54  Cu_30    -16.12   -16.097309 -0.022691   0.022691             ML    Set_6
55  Cu_36    -17.42   -17.491648  0.071648   0.071648             ML    Set_6
56  Cu_42    -17.03   -17.202557  0.172557   0.172557             ML    Set_6
57  Cu_48    -16.98   -17.001493  0.021493   0.021493             ML    Set_6
58  Cu_54    -15.61   -15.935366  0.325366   0.325366             ML    Set_6
59  Cu_60    -14.93   -15.228552  0.298552   0.298552             ML    Set_6

In [17]:
all_prediction_tables["FULL"]

    Dimer  Actual_E  Predicted_E     Error  Abs_Error Descriptor_Set Test_Set
0    Cu_1     -6.64    -8.162428  1.522428   1.522428           FULL    Set_1
1    Cu_7     -8.70    -8.688719 -0.011281   0.011281           FULL    Set_1
2   Cu_13     -9.13    -9.130925  0.000925   0.000925           FULL    Set_1
3   Cu_19    -10.32    -8.806396 -1.513604   1.513604           FULL    Set_1
4   Cu_25     -6.28    -8.959465  2.679465   2.679465           FULL    Set_1
5   Cu_31    -17.17   -16.687786 -0.482214   0.482214           FULL    Set_1
6   Cu_37    -15.90   -16.219679  0.319679   0.319679           FULL    Set_1
7   Cu_43    -17.41   -17.258877 -0.151123   0.151123           FULL    Set_1
8   Cu_49    -17.14   -17.106043 -0.033957   0.033957           FULL    Set_1
9   Cu_55    -16.31   -16.042290 -0.267710   0.267710           FULL    Set_1
10   Cu_2     -8.08    -7.547800 -0.532200   0.532200           FULL    Set_2
11   Cu_8     -8.66    -9.068416  0.408416   0.408416           FULL    Set_2
12  Cu_14     -9.52    -9.426059 -0.093941   0.093941           FULL    Set_2
13  Cu_20     -9.33    -8.182003 -1.147997   1.147997           FULL    Set_2
14  Cu_26    -16.40   -16.175690 -0.224310   0.224310           FULL    Set_2
15  Cu_32    -15.37   -15.543368  0.173368   0.173368           FULL    Set_2
16  Cu_38    -17.01   -16.934299 -0.075701   0.075701           FULL    Set_2
17  Cu_44    -15.98   -16.162752  0.182752   0.182752           FULL    Set_2
18  Cu_50    -17.28   -17.310656  0.030656   0.030656           FULL    Set_2
19  Cu_56    -16.64   -16.816723  0.176723   0.176723           FULL    Set_2
20   Cu_3     -7.94    -8.348351  0.408351   0.408351           FULL    Set_3
21   Cu_9     -9.18    -8.473364 -0.706636   0.706636           FULL    Set_3
22  Cu_15     -8.08    -7.955443 -0.124557   0.124557           FULL    Set_3
23  Cu_21     -7.46    -8.051016  0.591016   0.591016           FULL    Set_3
24  Cu_27    -17.36   -17.166607 -0.193393   0.193393           FULL    Set_3
25  Cu_33    -16.31   -16.112696 -0.197304   0.197304           FULL    Set_3
26  Cu_39    -15.66   -15.731759  0.071759   0.071759           FULL    Set_3
27  Cu_45    -16.92   -16.811438 -0.108562   0.108562           FULL    Set_3
28  Cu_51    -15.90   -16.150284  0.250284   0.250284           FULL    Set_3
29  Cu_57    -16.86   -16.325972 -0.534028   0.534028           FULL    Set_3
30   Cu_4     -8.30    -8.176651 -0.123349   0.123349           FULL    Set_4
31  Cu_10     -7.51    -8.168677  0.658677   0.658677           FULL    Set_4
32  Cu_16     -9.17    -8.948192 -0.221808   0.221808           FULL    Set_4
33  Cu_22     -7.97    -8.137112  0.167112   0.167112           FULL    Set_4
34  Cu_28    -17.49   -17.063786 -0.426214   0.426214           FULL    Set_4
35  Cu_34    -17.13   -16.993151 -0.136849   0.136849           FULL    Set_4
36  Cu_40    -16.22   -16.289200  0.069200   0.069200           FULL    Set_4
37  Cu_46    -15.47   -15.729811  0.259811   0.259811           FULL    Set_4
38  Cu_52    -16.90   -16.843847 -0.056153   0.056153           FULL    Set_4
39  Cu_58    -15.31   -15.521998  0.211998   0.211998           FULL    Set_4
40   Cu_5     -5.45    -7.622032  2.172032   2.172032           FULL    Set_5
41  Cu_11     -8.37    -8.882575  0.512575   0.512575           FULL    Set_5
42  Cu_17    -10.20   -15.633750  5.433750   5.433750           FULL    Set_5
43  Cu_23     -8.05    -8.964772  0.914772   0.914772           FULL    Set_5
44  Cu_29    -17.65   -17.458546 -0.191454   0.191454           FULL    Set_5
45  Cu_35    -17.29   -17.075190 -0.214810   0.214810           FULL    Set_5
46  Cu_41    -17.02   -16.991827 -0.028173   0.028173           FULL    Set_5
47  Cu_47    -16.11   -16.171314  0.061314   0.061314           FULL    Set_5
48  Cu_53    -15.60   -15.443160 -0.156840   0.156840           FULL    Set_5
49  Cu_59    -16.33   -15.680014 -0.649986   0.649986           FULL    Set_5
50   Cu_6     -8.58    -8.568510 -0.011490   0.011490           FULL    Set_6
51  Cu_12     -9.24    -8.841819 -0.398181   0.398181           FULL    Set_6
52  Cu_18     -9.82    -9.468808 -0.351192   0.351192           FULL    Set_6
53  Cu_24     -8.68    -8.698152  0.018152   0.018152           FULL    Set_6
54  Cu_30    -16.12   -16.325937  0.205937   0.205937           FULL    Set_6
55  Cu_36    -17.42   -17.441078  0.021078   0.021078           FULL    Set_6
56  Cu_42    -17.03   -17.284691  0.254691   0.254691           FULL    Set_6
57  Cu_48    -16.98   -16.721664 -0.258336   0.258336           FULL    Set_6
58  Cu_54    -15.61   -15.634566  0.024566   0.024566           FULL    Set_6
59  Cu_60    -14.93   -15.407876  0.477876   0.477876           FULL    Set_6

In [18]:
# =========================================================
# SAVE VALIDATION SUMMARY
# =========================================================

validation_summary.to_csv(
    "Validation_Summary.csv",
    index=False
)

print(
    "Saved: Validation_Summary.csv"
)

PermissionError: [Errno 13] Permission denied: 'Validation_Summary.csv'

In [ ]:
# =========================================================
# SAVE QM PREDICTIONS
# =========================================================

all_prediction_tables["QM"].to_csv(
    "QM_All_Predictions.csv",
    index=False
)

print(
    "Saved: QM_All_Predictions.csv"
)

In [ ]:
# =========================================================
# SAVE ML PREDICTIONS
# =========================================================

all_prediction_tables["ML"].to_csv(
    "ML_All_Predictions.csv",
    index=False
)

print(
    "Saved: ML_All_Predictions.csv"
)

In [ ]:
# =========================================================
# SAVE FULL PREDICTIONS
# =========================================================

all_prediction_tables["FULL"].to_csv(
    "FULL_All_Predictions.csv",
    index=False
)

print(
    "Saved: FULL_All_Predictions.csv"
)

In [ ]:
# =========================================================
# ACTUAL vs PREDICTED PLOT
# =========================================================

def plot_actual_vs_predicted(
    prediction_df,
    descriptor_name
):

    plt.figure(
        figsize=(7,7)
    )

    colors = {

        "Set_1": "red",
        "Set_2": "blue",
        "Set_3": "green",
        "Set_4": "orange",
        "Set_5": "purple",
        "Set_6": "brown"
    }

    for set_name, color in colors.items():

        subset = prediction_df[

            prediction_df["Test_Set"]

            ==

            set_name

        ]

        plt.scatter(

            subset["Actual_E"],

            subset["Predicted_E"],

            label=set_name,

            color=color,

            s=60

        )

    # --------------------------------------------
    # OVERALL METRICS
    # --------------------------------------------

    actual = prediction_df["Actual_E"]

    predicted = prediction_df["Predicted_E"]

    r2 = r2_score(
        actual,
        predicted
    )

    mae = mean_absolute_error(
        actual,
        predicted
    )

    rmse = np.sqrt(
        mean_squared_error(
            actual,
            predicted
        )
    )

    min_val = min(
        actual.min(),
        predicted.min()
    )

    max_val = max(
        actual.max(),
        predicted.max()
    )

    plt.plot(

        [min_val,max_val],

        [min_val,max_val],

        "k--",

        linewidth=2

    )

    plt.xlabel(
        "Actual Interaction Energy"
    )

    plt.ylabel(
        "Predicted Interaction Energy"
    )

    plt.title(
        f"{descriptor_name} Validation"
    )

    plt.text(

        0.05,

        0.95,

        f"R² = {r2:.4f}\n"
        f"MAE = {mae:.3f}\n"
        f"RMSE = {rmse:.3f}",

        transform=plt.gca().transAxes,

        verticalalignment="top"

    )

    plt.legend()

    plt.tight_layout()

    plt.show()

In [ ]:
# =========================================================
# GENERATE VALIDATION PLOTS
# =========================================================

for descriptor_name in descriptor_sets.keys():

    plot_actual_vs_predicted(

        all_prediction_tables[
            descriptor_name
        ],

        descriptor_name

    )

In [ ]:
# =========================================================
# QM vs ML vs FULL
# =========================================================

plt.figure(
    figsize=(8,8)
)

descriptor_colors = {

    "QM"  : "red",

    "ML"  : "blue",

    "FULL": "green"
}

for descriptor_name, color in descriptor_colors.items():

    prediction_df = all_prediction_tables[
        descriptor_name
    ]

    plt.scatter(

        prediction_df["Actual_E"],

        prediction_df["Predicted_E"],

        color=color,

        label=descriptor_name,

        s=70,

        alpha=0.8,

        edgecolors="black"

    )

all_actual = pd.concat([

    all_prediction_tables["QM"]["Actual_E"],

    all_prediction_tables["ML"]["Actual_E"],

    all_prediction_tables["FULL"]["Actual_E"]

])

all_predicted = pd.concat([

    all_prediction_tables["QM"]["Predicted_E"],

    all_prediction_tables["ML"]["Predicted_E"],

    all_prediction_tables["FULL"]["Predicted_E"]

])

min_val = min(
    all_actual.min(),
    all_predicted.min()
)

max_val = max(
    all_actual.max(),
    all_predicted.max()
)

plt.plot(

    [min_val,max_val],

    [min_val,max_val],

    "k--",

    linewidth=2

)

plt.xlabel(
    "Actual Interaction Energy"
)

plt.ylabel(
    "Predicted Interaction Energy"
)

plt.title(
    "Descriptor Set Comparison"
)

plt.legend()

plt.tight_layout()

plt.show()

In [ ]:
plot_actual_vs_predicted(
    all_prediction_tables["QM"],
    "QM",
    "red"
)

plot_actual_vs_predicted(
    all_prediction_tables["ML"],
    "ML",
    "blue"
)

plot_actual_vs_predicted(
    all_prediction_tables["FULL"],
    "FULL",
    "green"
)

In [ ]:
# =========================================================
# ACTUAL vs PREDICTED PLOT
# =========================================================

def plot_actual_vs_predicted(
    prediction_df,
    descriptor_name,
    color
):

    # --------------------------------------------------
    # FONT SETTINGS
    # --------------------------------------------------

    plt.rcParams["font.family"] = "Times New Roman"
    plt.rcParams["font.size"] = 12
    plt.rcParams["font.weight"] = "bold"

    actual = prediction_df["Actual_E"]
    predicted = prediction_df["Predicted_E"]

    r2 = r2_score(
        actual,
        predicted
    )

    mae = mean_absolute_error(
        actual,
        predicted
    )

    rmse = np.sqrt(
        mean_squared_error(
            actual,
            predicted
        )
    )

    # --------------------------------------------------
    # CREATE FIGURE
    # --------------------------------------------------

    plt.figure(
        figsize=(7,7)
    )

    plt.scatter(

        actual,

        predicted,

        color=color,

        s=90,

        alpha=0.85,

        edgecolors="black",

        linewidth=1.5

    )

    # --------------------------------------------------
    # DIAGONAL REFERENCE LINE
    # --------------------------------------------------

    min_val = min(
        actual.min(),
        predicted.min()
    )

    max_val = max(
        actual.max(),
        predicted.max()
    )

    plt.plot(

        [min_val, max_val],

        [min_val, max_val],

        linestyle="--",

        color="black",

        linewidth=2.5

    )

    # --------------------------------------------------
    # AXIS LABELS
    # --------------------------------------------------

    plt.xlabel(

        "Actual Interaction Energy (kcal/mol)",

        fontsize=12,

        fontweight="bold"

    )

    plt.ylabel(

        "Predicted Interaction Energy (kcal/mol)",

        fontsize=12,

        fontweight="bold"

    )

    plt.title(

        f"{descriptor_name} Validation",

        fontsize=12,

        fontweight="bold"

    )

    # --------------------------------------------------
    # METRICS
    # --------------------------------------------------

    plt.text(

        0.05,

        0.95,

        f"R$^2$ = {r2:.4f}\n"
        f"MAE = {mae:.3f}\n"
        f"RMSE = {rmse:.3f}",

        transform=plt.gca().transAxes,

        fontsize=12,

        fontweight="bold",

        verticalalignment="top"

    )

    # --------------------------------------------------
    # AXES STYLE
    # --------------------------------------------------

    ax = plt.gca()

    ax.set_xlim(min_val, max_val)
    ax.set_ylim(min_val, max_val)

    ax.tick_params(

        axis="both",

        direction="in",

        length=6,

        width=2,

        labelsize=12

    )

    for tick in ax.get_xticklabels():
        tick.set_fontweight("bold")

    for tick in ax.get_yticklabels():
        tick.set_fontweight("bold")

    for spine in ax.spines.values():

        spine.set_linewidth(2)

    # --------------------------------------------------
    # SAVE
    # --------------------------------------------------

    plt.tight_layout()

    plt.savefig(

        f"{descriptor_name}_Actual_vs_Predicted.png",

        dpi=600,

        bbox_inches="tight"

    )

    print(
        f"Saved: {descriptor_name}_Actual_vs_Predicted.png"
    )

    plt.show()

In [ ]:
plot_actual_vs_predicted(
    all_prediction_tables["QM"],
    "QM",
    "red"
)

plot_actual_vs_predicted(
    all_prediction_tables["ML"],
    "ML",
    "blue"
)

plot_actual_vs_predicted(
    all_prediction_tables["FULL"],
    "FULL",
    "green"
)

In [ ]:
# =========================================================
# ML SHAP ANALYSIS
# =========================================================

X_ml = df[ml_columns]

y_ml = df["E"]

scaler_ml = StandardScaler()

X_ml_scaled = pd.DataFrame(

    scaler_ml.fit_transform(
        X_ml
    ),

    columns=ml_columns
)

ml_model = XGBRegressor(
    **xgb_params
)

ml_model.fit(
    X_ml_scaled,
    y_ml
)

In [ ]:
# =========================================================
# CALCULATE SHAP VALUES
# =========================================================

explainer_ml = shap.TreeExplainer(
    ml_model
)

shap_values_ml = (
    explainer_ml.shap_values(
        X_ml_scaled
    )
)

In [ ]:
# =========================================================
# SHAP SUMMARY PLOT
# =========================================================

shap.summary_plot(

    shap_values_ml,

    X_ml_scaled,

    show=False

)

plt.tight_layout()

plt.savefig(

    "ML_SHAP_Summary.png",

    dpi=600,

    bbox_inches="tight"

)

print(
    "Saved: ML_SHAP_Summary.png"
)

plt.show()

In [ ]:
# =========================================================
# SHAP TABLE
# =========================================================

ml_shap_table = pd.DataFrame({

    "Feature":
        X_ml_scaled.columns,

    "Mean_Abs_SHAP":
        np.abs(
            shap_values_ml
        ).mean(axis=0)

})

ml_shap_table = (

    ml_shap_table

    .sort_values(

        "Mean_Abs_SHAP",

        ascending=False

    )

    .reset_index(drop=True)

)

ml_shap_table.to_csv(

    "ML_SHAP_Table.csv",

    index=False

)

print(
    "Saved: ML_SHAP_Table.csv"
)

ml_shap_table

In [ ]:
# =========================================================
# FULL SHAP ANALYSIS
# =========================================================

X_full = df[full_columns]

y_full = df["E"]

scaler_full = StandardScaler()

X_full_scaled = pd.DataFrame(

    scaler_full.fit_transform(
        X_full
    ),

    columns=full_columns
)

full_model = XGBRegressor(
    **xgb_params
)

full_model.fit(
    X_full_scaled,
    y_full
)

In [ ]:
# =========================================================
# CALCULATE SHAP VALUES
# =========================================================

explainer_full = shap.TreeExplainer(
    full_model
)

shap_values_full = (

    explainer_full.shap_values(
        X_full_scaled
    )

)

In [ ]:
# =========================================================
# SHAP SUMMARY PLOT
# =========================================================

shap.summary_plot(

    shap_values_full,

    X_full_scaled,

    show=False

)

plt.tight_layout()

plt.savefig(

    "FULL_SHAP_Summary.png",

    dpi=600,

    bbox_inches="tight"

)

print(
    "Saved: FULL_SHAP_Summary.png"
)

plt.show()

In [ ]:
# =========================================================
# SHAP TABLE
# =========================================================

full_shap_table = pd.DataFrame({

    "Feature":
        X_full_scaled.columns,

    "Mean_Abs_SHAP":
        np.abs(
            shap_values_full
        ).mean(axis=0)

})

full_shap_table = (

    full_shap_table

    .sort_values(

        "Mean_Abs_SHAP",

        ascending=False

    )

    .reset_index(drop=True)

)

full_shap_table.to_csv(

    "FULL_SHAP_Table.csv",

    index=False

)

print(
    "Saved: FULL_SHAP_Table.csv"
)

full_shap_table